### ISSUE TITLE
Cannot build Release MSBuild due to PrintLineDebugger

### ISSUE THREAD

**Issue by ccastanedaucf** [Microsoft/msbuild#3945]
Seems to have been introduced by #3878 

### Steps to reproduce

Build MSBuild with ```build -configuration Release``` on the latest tip of master

### Expected  behavior
Builds successfully

### Actual behavior
Fails to build with the following errors:
```
Build FAILED.

C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Framework.UnitTests\Microsoft.Build.Framework.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Framework.UnitTests\Microsoft.Build.Framework.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Build.OM.UnitTests\Microsoft.Build.Engine.OM.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Build.OM.UnitTests\Microsoft.Build.Engine.OM.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Tasks.UnitTests\Microsoft.Build.Tasks.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Tasks.UnitTests\Microsoft.Build.Tasks.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\MSBuild.UnitTests\Microsoft.Build.CommandLine.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Utilities.UnitTests\Microsoft.Build.Utilities.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Utilities.UnitTests\Microsoft.Build.Utilities.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Build.UnitTests\Microsoft.Build.Engine.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\MSBuild.UnitTests\Microsoft.Build.CommandLine.UnitTests.csproj]
C:\src\msbuild\src\Shared\UnitTests\TestEnvironment.cs(683,26): error CS0246: The type or namespace name 'PrintLineDebugger' could not be found (are you missing a using directive or an assem
bly reference?) [C:\src\msbuild\src\Build.UnitTests\Microsoft.Build.Engine.UnitTests.csproj]
    0 Warning(s)
    12 Error(s)
```

**Comment by ccastanedaucf** [comment]
Closed by #3946

**Comment by ccastanedaucf** [comment]
```build -test -configuration Release``` fails after #3946

**Comment by livarcocc** [comment]
May have been addressed by https://github.com/Microsoft/msbuild/pull/3949?

**Comment by ccastanedaucf** [comment]
Closed by #3949
