### ISSUE TITLE
Exclusion to glob not being honored in some cases

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#2621]
[repro2.zip](https://github.com/Microsoft/msbuild/files/1373848/repro2.zip) (contents described below)

## Test.proj:
``` xml
<Project>
  <Target Name="Build">
    <ItemGroup>
      <_NETStandardLibraryNETFrameworkLib Include="$(MSBuildThisFileDirectory)\net47\lib\*.txt" />
      <_NETStandardLibraryNETFrameworkLib Include="$(MSBuildThisFileDirectory)\net461\lib\*.txt"
                                          Exclude="@(_NETStandardLibraryNETFrameworkLib->'$(MSBuildThisFileDirectory)\net461\lib\%(FileName).txt')" />
     </ItemGroup>          

     <Message Importance="High" Text="%(_NETStandardLibraryNETFrameworkLib.FullPath)" />
  </Target>

</Project>
```

## On disk next to test.proj, two empty files
*  net47\lib\System.ValueTuple.txt
*  net461\lib\System.ValueTuple.txt

## Build using dogfood 15.5 msbuild on my machine --> exclusion works
```
> D:\Src\q>msbuild /v:m
Microsoft (R) Build Engine version 15.5.90.54627 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  D:\Src\q\net47\lib\System.ValueTuple.txt
```

## Build using latest master --> exclusion does not work
```
Microsoft (R) Build Engine version 15.5.139.63946 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  D:\Src\q\net47\lib\System.ValueTuple.txt
  D:\Src\q\net461\lib\System.ValueTuple.txt
```

## Note
Above is a simulation of the real code [here](https://github.com/dotnet/sdk/blob/865bebd0086a7fc097327eeca075feda33d08a85/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L60-L70)

It manifests in real scenarios as the wrong version of System.ValueTuple.dll being used with net47 library referencing netstandard2.0 library, causing duplicate definitions of ValueTuple to conflict:
```
    NETFramework.cs(10,9): error CS0433: The type 'ValueTuple<T1, T2>' exists in both 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 
    'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

@davkean @AndyGerlicher

**Comment by davkean** [comment]
@cdmihai This looks like a regression in the new globs changed, can we take a look before we insert this?

**Comment by cdmihai** [comment]
Most likely #2557 regressed this somehow. I'll take a look.

**Comment by cdmihai** [comment]
Fixed in #2644
