### PR TITLE
Target item includes use same code as Project item includes

### LINKED ISSUE #2621: Exclusion to glob not being honored in some cases
[repro2.zip](https://github.com/Microsoft/msbuild/files/1373848/repro2.zip) (contents described below)

## Test.proj:
``` xml
<Project>
  <Target Name="Build">
    <ItemGroup>
      <_NETStandardLibraryNETFrameworkLib Include="$(MSBuildThisFileDirectory)\net47\lib\*.txt" />
      <_NETStandardLibraryNETFrameworkLib Include="$(MSBuildThisFileDirectory)\net461\lib\*.txt"
                                          Exclude="@(_NETStandardLibraryNETFrameworkLib->'$(MSBuildThisFileDirectory)\net461\lib\%(FileName).txt')" />
     </ItemGroup>          

     <Message Importance="High" Text="%(_NETStandardLibraryNETFrameworkLib.FullPath)" />
  </Target>

</Project>
```

## On disk next to test.proj, two empty files
*  net47\lib\System.ValueTuple.txt
*  net461\lib\System.ValueTuple.txt

## Build using dogfood 15.5 msbuild on my machine --> exclusion works
```
> D:\Src\q>msbuild /v:m
Microsoft (R) Build Engine version 15.5.90.54627 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  D:\Src\q\net47\lib\System.ValueTuple.txt
```

## Build using latest master --> exclusion does not work
```
Microsoft (R) Build Engine version 15.5.139.63946 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  D:\Src\q\net47\lib\System.ValueTuple.txt
  D:\Src\q\net461\lib\System.ValueTuple.txt
```

## Note
Above is a simulation of the real code [here](https://github.com/dotnet/sdk/blob/865bebd0086a7fc097327eeca075feda33d08a85/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L60-L70)

It manifests in real scenarios as the wrong version of System.ValueTuple.dll being used with net47 library referencing netstandard2.0 library, causing duplicate definitions of ValueTuple to conflict:
```
    NETFramework.cs(10,9): error CS0433: The type 'ValueTuple<T1, T2>' exists in both 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 
    'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

@davkean @AndyGerlicher

### PR DESCRIPTION
**Pull request by cdmihai**
Fixes #2621 

This brings the exclude optimization (sending excludes together with includes, rather than file walking twice and doing set difference) to target based item includes as well, so it should make target item globbing a bit faster.

### CODE REVIEW

**Comment by cdmihai** [comment]
Looks like this change regresses design time builds :(

I'll investigate alternative ways of fixing it.

### Evaluation: Time (ms)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :white_check_mark: | yes | 90.9084 -> 90.6195 (-0.318%)
DotnetWebProject | :white_check_mark: | yes | 135.0422 -> 132.9875 (-1.522%)
DotnetMvcProject | :red_circle: | yes | 157.5841 -> 158.1426 (0.354%)
Picasso | :red_circle: | yes | 757.5154 -> 767.9676 (1.38%)
SmallP2POldCsproj | :white_check_mark: | yes | 130.4592 -> 129.7581 (-0.537%)
SmallP2PNewCsproj | :red_circle: | yes | 238.4698 -> 242.3065 (1.609%)
Generated_100_100_v150 | ::ok_hand: | no | 1716.0335 -> 1679.8501 (-2.109%)
LargeP2POldCsproj | ::ok_hand: | no | 2207.3645 -> 2202.7731 (-0.208%)
roslyn | :white_check_mark: | yes | 9606.1598 -> 9484.1742 (-1.27%)

### Evaluation: Memory (bytes)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | ::ok_hand: | no | 4879110 -> 4878677 (-0.009%)
DotnetWebProject | ::ok_hand: | no | 6551103 -> 6550660 (-0.007%)
DotnetMvcProject | ::ok_hand: | no | 7395517 -> 7394641 (-0.012%)
Picasso | ::ok_hand: | no | 34321577 -> 34321400 (-0.001%)
SmallP2POldCsproj | :ok_hand: | no | 5878864 -> 5879005 (0.002%)
SmallP2PNewCsproj | ::ok_hand: | no | 10331823 -> 10331750 (-0.001%)
Generated_100_100_v150 | ::ok_hand: | no | 143455248 -> 143455158 (0%)
LargeP2POldCsproj | :ok_hand: | no | 83923320 -> 83924935 (0.002%)
roslyn | :ok_hand: | no | 397710353 -> 401386927 (0.924%)

### Build: Time (ms)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :ok_hand: | no | 23.3261 -> 23.3677 (0.178%)
DotnetWebProject | :ok_hand: | no | 28.53 -> 28.5891 (0.207%)
DotnetMvcProject | :red_circle: | yes | 30.959 -> 31.2211 (0.847%)
Picasso | :red_circle: | yes | 7002.2978 -> 7054.4939 (0.745%)
SmallP2POldCsproj | :red_circle: | yes | 259.1287 -> 259.989 (0.332%)
SmallP2PNewCsproj | :red_circle: | yes | 253.8485 -> 259.3147 (2.153%)

### Build: Memory (bytes)
Test | Overall | Significant δ  | Value
:--- | :--- | :--- | :---
DotnetConsoleProject | :red_circle: | yes | 1153507 -> 1162527 (0.782%)
DotnetWebProject | :red_circle: | yes | 1275911 -> 1288486 (0.986%)
DotnetMvcProject | :red_circle: | yes | 1446333 -> 1461378 (1.04%)
Picasso | ::ok_hand: | no | 268916932 -> 267520319 (-0.519%)
SmallP2POldCsproj | :red_circle: | yes | 9617983 -> 9643501 (0.265%)
SmallP2PNewCsproj | :red_circle: | yes | 9734760 -> 9775518 (0.419%)

**Comment by cdmihai** [comment]
Apparently this severely degrades perf when there are many excludes. For example, building a `dotnet new razor` project takes 5 minutes instead of the usual 3 seconds.

Top targets
```
      129 ms  FindReferenceAssembliesForReferences       1 calls
      157 ms  ReportAssetsLogMessages                    1 calls
      165 ms  _ComputeTransitiveProjectReferences        1 calls
      263 ms  RunResolvePackageDependencies              1 calls
      801 ms  ResolveAssemblyReferences                  1 calls
    49791 ms  RunProduceContentAssets                    1 calls
    51732 ms  _HandlePackageFileConflicts                1 calls
    57129 ms  _ComputeLockFileReferences                 1 calls
    154289 ms  _ComputeLockFileCopyLocal                  1 calls
```
For example, executing [this item](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L386) takes 48 seconds, 377 items are produced and 3976 are excluded.

This happens because of [this line](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs#L72) which does expensive file normalization `included Items * exclude items *2` times. For the previous example it performs `377 * 3976 * 2 = 2997904 `normalizations.

**Comment by dasMulli** [comment]
I suppose this may also resolve https://github.com/Microsoft/msbuild/issues/2491?

**Comment by cdmihai** [comment]
Replaced by #2644

**Comment by cdmihai** [comment]
@dasMulli This actually PR probably would, but sadly it introduces a big perf regression. The alternative fix, #2644, does not fix it.
