### ISSUE TITLE
Invoking /langversion:?

### ISSUE THREAD

**Issue by eduherminio** [Microsoft/msbuild#3663]
When using an old version of MSBuild tools, the following error shows up when trying to compile using C# 7.3.

`CSC : error CS1617: Invalid option '7.3' for /langversion. Use '/langversion:?' to list supported values.`

I am not being able to invoke that `/langversion:?` to check available language versions.

How could I do it?

**Comment by rainersigwald** [comment]
The version of MSBuild by default influences the version of the C# compiler that gets used (since we both ship inside Visual Studio). Where did this version of MSBuild come from, and what version is it? This error suggests that the compiler predates the 7.3 version of the C# language.

**Comment by eduherminio** [comment]
Don't get me wrong, I'm aware I have to update MSBuild tools to solve the error, I'm only curious about that `/langversion:?` the error suggests, which I don't know how (or where) to invoke.

**Comment by rainersigwald** [comment]
Ah, I see. That's a somewhat misleading error, because it refers to a `csc.exe` command-line parameter, which you should normally not specify because you can use MSBuild properties to specify the language version. To see what's currently supported, find the path to `csc.exe` that was invoked (it should be in your build log; if it's not you might try capturing higher verbosity logs). `csc.exe` may also be in your environment's `PATH`.

On my machine, in a Developer Command Prompt for VS 2017, I get

```
s:\msbuild>csc.exe /langversion:?
Supported language versions:
default
1
2
3
4
5
6
7.0 (default)
7.1
7.2
7.3 (latest)
latest
```

cc @jaredpar for feedback on confusion around the langversion error message when triggered through MSBuild.

**Comment by eduherminio** [comment]
That makes sense, thank you!
