### ISSUE TITLE
csc.exe error with any arguments due to Microsoft.CodeAnalysis.CSharp.dll missing from BuildTools install

### ISSUE THREAD

**Issue by loop-evgeny** [Microsoft/msbuild#2866]
### Steps to reproduce
Install VS 2017 Build Tools from https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15 (but not VS itself). Select none of the workloads and the following individual components:
- .NET Framework 3.5 development tools
- .NET Framework 4.5 targeting pack
- .NET Framework 4.5.1 targeting pack
- .NET Framework 4.5.2 targeting pack
- .NET Framework 4.6.2 SDK
- .NET Framework 4.6.2 targeting pack
- F# compiler
- NuGet targets and build tasks

Open Developer Command Prompt for VS 2017 and run ```csc``` (with no arguments)

### Expected  behavior
```
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified
```

### Actual behavior
```
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```

### Environment data
`msbuild /version` output: 15.5.180.51428

OS info: Windows Server 2016 x64

### Workaround

Copy ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CodeAnalysis.CSharp.dll``` from a machine with VS 2017 installed to ```C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\``` on the machine experiencing the problem.

**Comment by rainersigwald** [comment]
I don't repro this on a fresh install, which seems to be `Visual Studio Build Tools 2017 15.5.4`:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>msbuild /version
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.5.180.51428
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>where csc
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\csc.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>csc.exe
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified
```

Have you tried repairing the Build Tools installation? Have you reproduced this on another machine?

**Comment by loop-evgeny** [comment]
I had Build Tools 15.5.0 installed, which I updated to 15.5.4 (using a freshly downloaded installer). Running Repair from the installer (after the update to 15.5.4) fixed it.

So either there was a bug in the earlier installer version or something went wrong with my installation. (I followed the same steps on 2 machines, though, with the same results.)

**Comment by rainersigwald** [comment]
If anyone sees this again or has an idea about what might have gone wrong, please comment here and we'll reopen. Closing for now since it seems to have disappeared.
